ggplot(data=mpg) + geom_point(mapping = aes(x = displ, y = hwy)) + facet_grid(drv ~ cyl)
ggplot(data=mpg) + geom_point(mapping = aes(x = displ, y = hwy))
ggplot(data = mpg) + geom_smooth(mapping = aes(x = displ, y = hwy))
ggplot(data=mpg) + geom_smooth(mapping = aes(x = displ, y = hwy, linetype = drv, color = drv))
ggplot(data=mpg) + geom_smooth(mapping = aes(x = displ, y = hwy, group = drv))
ggplot(data = mpg) + geom_smooth(mapping = aes(x = displ, y = hwy, color = drv), show.legend = TRUE)
ggplot(data = mpg)+ geom_point(mapping = aes(x = displ, y = hwy,)) + geom_smooth(mapping = aes(x = displ, y = hwy))
ggplot(data=mpg, mapping = aes(x = displ, y = hwy)) + geom_point() + geom_smooth()
ggplot(data=mpg, mapping = aes(x = displ, y = hwy)) + geom_point(mapping = aes(color = class)) + geom_smooth()
ggplot(data = mpg, mapping = aes(x = displ, y = hwy)) + geom_point(mapping = aes(color = class)) + geom_smooth(data = filter(mpg, class == "subcompact"), se = FALSE)
ggplot(data=mpg, mapping = aes(x = displ, y = hwy)) + geom_point(mapping = aes(color = class)) + geom_smooth(data = filter(mpg, class=="subcompact"), se = FALSE)
ggplot(data = diamonds) + geom_bar(mapping = aes(x = cut, color = cut))
ggplot(data = diamonds) + stat_count(mapping = aes(x = cut))
ggplot(data = diamonds)+ geom_bar(mapping = aes(x = cut, fill = cut))
ggplot(data = diamonds) + geom_bar(mapping = aes(x = cut, fill = clarity))
?diamonds
ggplot(data = diamonds, mapping = aes(x = cut, fill = clarity)) + geom_bar(alpha = 1/5, position = "identity")
ggplot(data=diamonds, mapping = aes(x = cut, color = clarity)) + geom_bar(fill = NA, position = "identity")
ggplot(data = diamonds) + geom_bar(mapping = aes(x = cut, fill = clarity), position = "fill")
ggplot(data = diamonds) + geom_bar(mapping = aes(x = cut, fill = clarity), position = "dodge")
ggplot(data=mpg) + geom_point(mapping = aes(x = displ, y = hwy), position = "jitter")
ggplot(data=mpg, mapping = aes(x = class, y = hwy)) + geom_boxplot()
ggplot(data=mpg, mapping = aes(x = class, y = hwy)) + geom_boxplot() + coord_flip()
ggplot(data=diamonds)+ geom_bar(mapping = aes(x = cut, fill = cut), show.legend = FALSE, width = 1) + theme(aspect.ratio = 1) + labs(x = NULL, y = NULL)
graph_1 <- ggplot(data=diamonds)+ geom_bar(mapping = aes(x = cut, fill = cut), show.legend = FALSE, width = 1) + theme(aspect.ratio = 1) + labs(x = NULL, y = NULL)
graph_1 + coord_flip()
graph_1 + coord_polar()
install.packages("nycflights13")
library(nycflights13)
library(tidyverse)
flights
head(flights)
filter(flights, month==5, day==28)
flights%>% filter(month==5, day==28)
jan1 <- filter(flights, month == 1, day == 1)
(jul4 <- filter(flights, month == 7, day ==4))
flights %>% filter(month = 7, day = 4)
sqrt(2)^2 == 2; near(sqrt(2)^2, 2)
1/33*33 == 1; near(1/33*33, 1)
1/49*49 == 1; near(1/49*49, 1)
8 | 9
flights %>% filter(month == 1 | month == 2)
flights %>% filter(month %in% c(1, 2))
